image:
  registry: quay.io
  repository: cybozu/promtail
  tag: 2.6.1.1

containerSecurityContext:
  readOnlyRootFilesystem: true
  capabilities:
    add:
      - DAC_READ_SEARCH
    drop:
      - ALL
  allowPrivilegeEscalation: false

extraVolumes:
  - hostPath:
      path: /var/log/audit
    name: audit
  - hostPath:
      path: /run/log/journal
    name: journal

extraVolumeMounts:
  - name: audit
    mountPath: /var/log/audit
    readOnly: true
  - name: journal
    mountPath: /var/log/journal
    readOnly: true

extraArgs:
  - "-config.expand-env=true"

config:
  clients:
    - url: http://distributor.logging:3100/loki/api/v1/push
  snippets:
    extraScrapeConfigs: |
      #
      # Added by neco
      #
      - job_name: kubernetes-apiservers
        static_configs:
          - targets:
              - localhost
            labels:
              job: kubernetes-apiservers
              __path__: /var/log/audit/*.log
        relabel_configs:
          - target_label: type
            replacement: audit
          - target_label: instance
            replacement: ${HOSTNAME}
        pipeline_stages:
          - json:
              expressions:
                timestamp: stageTimestamp
          - timestamp:
              format: RFC3339Nano
              source: timestamp
      - job_name: journal
        journal:
          json: false
          max_age: 12h
          path: /var/log/journal
          labels:
            job: systemd-journal
            instance: ${HOSTNAME}
        relabel_configs:
          - source_labels: ["__journal__systemd_unit"]
            target_label: "unit"
          - source_labels: ["__journal__systemd_unit"]
            regex: ^session-\d+\.scope$
            target_label: "unit"
            replacement: session.scope
          - source_labels: ["__journal__systemd_unit"]
            regex: ^sshd@\d+-\d+\.\d+\.\d+\.\d+:\d+-\d+\.\d+\.\d+\.\d+:\d+\.service$
            target_label: "unit"
            replacement: sshd.service
          - source_labels: ["__journal_syslog_identifier"]
            target_label: "syslog_identifier"
          - source_labels: ["__journal_container_name"]
            target_label: "container_name"
          - source_labels: ["__journal__hostname"]
            target_label: "hostname"
