apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
resources:
  - ./upstream
images:
  - name: quay.io/cybozu/memcached
    newTag: 1.6.16.1
  - name: quay.io/cybozu/memcached-exporter
    newTag: 0.10.0.1
  - name: quay.io/cybozu/loki
    newTag: 2.7.1.1
