apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: loki
  namespace: monitoring
spec:
  name: loki.yaml
  datasources:
    - name: loki
      type: loki
      access: proxy
      url: http://query-frontend.logging.svc:3100
      version: 1
      isDefault: false
      editable: false
      jsonData:
        tlsSkipVerify: true
        timeInterval: "30s"
