apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: victoriametrics
spec:
  name: victoriametrics.yaml
  datasources:
    - name: vmsingle
      type: prometheus
      url: http://vmsingle-vmsingle.monitoring.svc:8429
    - name: vmcluster
      type: prometheus
      access: proxy
      url: http://vmselect-vmcluster.monitoring.svc:8481/select/0/prometheus
      version: 1
      isDefault: true
      editable: false
      jsonData:
        tlsSkipVerify: true
        timeInterval: "30s"
    - name: "vmcluster (vmstorage-0)"
      type: prometheus
      access: proxy
      url: http://vmselect-vmcluster-dedicated-0.vmselect-vmcluster-dedicated.monitoring.svc:8481/select/0/prometheus
      version: 1
      isDefault: false
      editable: false
      jsonData:
        tlsSkipVerify: true
        timeInterval: "30s"
    - name: "vmcluster (vmstorage-1)"
      type: prometheus
      access: proxy
      url: http://vmselect-vmcluster-dedicated-1.vmselect-vmcluster-dedicated.monitoring.svc:8481/select/0/prometheus
      version: 1
      isDefault: false
      editable: false
      jsonData:
        tlsSkipVerify: true
        timeInterval: "30s"
    - name: "vmcluster (vmstorage-2)"
      type: prometheus
      access: proxy
      url: http://vmselect-vmcluster-dedicated-2.vmselect-vmcluster-dedicated.monitoring.svc:8481/select/0/prometheus
      version: 1
      isDefault: false
      editable: false
      jsonData:
        tlsSkipVerify: true
        timeInterval: "30s"
