apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - manifests
  - datasources/loki.yaml
  - datasources/victoriametrics.yaml
  - grafana.yaml
  - upstream/cluster_roles/cluster_role_aggregate_grafana_admin_edit.yaml
  - upstream/cluster_roles/cluster_role_aggregate_grafana_view.yaml
  - upstream/cluster_roles/cluster_role_binding_grafana_operator.yaml
  - upstream/cluster_roles/cluster_role_grafana_operator.yaml
patchesStrategicMerge:
  - deployment.yaml
  - patch-grafana-operator-crds.yaml
images:
  - name: quay.io/grafana-operator/grafana-operator
    newName: quay.io/cybozu/grafana-operator
    newTag: 4.6.0.1
