apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: grafanadashboards.integreatly.org
spec:
  preserveUnknownFields: false
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: grafanadatasources.integreatly.org
spec:
  preserveUnknownFields: false
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: grafanas.integreatly.org
spec:
  preserveUnknownFields: false
