# permissions for end users to edit vmstaticscrapes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmstaticscrape-editor-role
rules:
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - vmstaticscrapes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - vmstaticscrapes/status
  verbs:
  - get
