nameReference:
  - kind: ConfigMap
    fieldSpecs:
      - kind: VMAlertmanager
        path: spec/configMaps
      - kind: VMAlertmanager
        path: spec/volumes/configMap/name
  - kind: Secret
    fieldSpecs:
      - kind: VMAgent
        path: spec/additionalScrapeConfigs/name
