apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - upstream/crd
  - upstream/rbac/vmagent_editor_role.yaml
  - upstream/rbac/vmagent_viewer_role.yaml
  - upstream/rbac/vmalert_editor_role.yaml
  - upstream/rbac/vmalert_viewer_role.yaml
  - upstream/rbac/vmalertmanager_editor_role.yaml
  - upstream/rbac/vmalertmanager_viewer_role.yaml
  - upstream/rbac/vmalertmanagerconfig_editor_role.yaml
  - upstream/rbac/vmalertmanagerconfig_viewer_role.yaml
  - upstream/rbac/vmpodscrape_editor_role.yaml
  - upstream/rbac/vmpodscrape_viewer_role.yaml
  - upstream/rbac/vmprobe_editor_role.yaml
  - upstream/rbac/vmprobe_viewer_role.yaml
  - upstream/rbac/vmrule_editor_role.yaml
  - upstream/rbac/vmrule_viewer_role.yaml
  - upstream/rbac/vmservicescrape_editor_role.yaml
  - upstream/rbac/vmservicescrape_viewer_role.yaml
  - upstream/rbac/vmstaticscrape_editor_role.yaml
  - upstream/rbac/vmstaticscrape_viewer_role.yaml
  - rules
  - rbac
  - operator.yaml
  - vmagent.yaml
  - vmcluster.yaml
  - vmselect-dedicated.yaml
  - vmsingle.yaml
images:
  - name: quay.io/cybozu/victoriametrics-vmselect
    newTag: 1.80.0.1
