apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: vmcluster-largeset
  namespace: monitoring
spec:
  vmstorage:
    replicaCount: 3
    extraArgs:
      dedup.minScrapeInterval: 30s # should be equal to VMAgent's scrapeInterval (default 30s)
    storage:
      volumeClaimTemplate:
        metadata:
          name: vmstorage
        spec:
          storageClassName: standard
          resources:
            requests:
              storage: 3Gi
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
    containers:
      - name: vmstorage
        livenessProbe:
          httpGet:
            path: /health
            port: 8482
            scheme: HTTP
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8482
          failureThreshold: 30
          periodSeconds: 30

  vmselect:
    replicaCount: 3
    extraArgs:
      replicationFactor: "2"
      dedup.minScrapeInterval: 30s # should be equal to VMAgent's scrapeInterval (default 30s)
    resources:
      requests:
        cpu: 100m
        memory: 500Mi

    # the following volumes and volumeMounts should be removed eventually
    volumes:
    - name: tmp
      emptyDir: {}
    volumeMounts:
    - name: tmp
      mountPath: /tmp

  vminsert:
    replicaCount: 3
    extraArgs:
      replicationFactor: "2"
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
