apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributor
  namespace: logging
spec:
  template:
    metadata:
      labels:
        gossip_ring_member: "true"
    spec:
      containers:
        - name: distributor
          resources:
            requests: null
            limits: null
          ports:
            - containerPort: 7946
              name: gossip-ring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-frontend
  namespace: logging
spec:
  template:
    spec:
      containers:
        - name: query-frontend
          resources:
            requests: null
            limits: null
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: table-manager
  namespace: logging
spec:
  template:
    spec:
      containers:
        - name: table-manager
          env:
            - name: BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: loki-data-bucket
                  key: BUCKET_NAME
            - name: BUCKET_HOST
              valueFrom:
                configMapKeyRef:
                  name: loki-data-bucket
                  key: BUCKET_HOST
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: loki-data-bucket
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-data-bucket
                  key: AWS_SECRET_ACCESS_KEY
          resources:
            requests: null
            limits: null
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: compactor
  namespace: logging
spec:
  template:
    spec:
      containers:
        - name: compactor
          env:
            - name: BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: loki-data-bucket
                  key: BUCKET_NAME
            - name: BUCKET_HOST
              valueFrom:
                configMapKeyRef:
                  name: loki-data-bucket
                  key: BUCKET_HOST
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: loki-data-bucket
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-data-bucket
                  key: AWS_SECRET_ACCESS_KEY
          resources:
            requests: null
            limits: null
      terminationGracePeriodSeconds: 30
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ingester
  namespace: logging
spec:
  template:
    metadata:
      labels:
        gossip_ring_member: "true"
    spec:
      containers:
        - name: ingester
          env:
            - name: BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: loki-data-bucket
                  key: BUCKET_NAME
            - name: BUCKET_HOST
              valueFrom:
                configMapKeyRef:
                  name: loki-data-bucket
                  key: BUCKET_HOST
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: loki-data-bucket
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-data-bucket
                  key: AWS_SECRET_ACCESS_KEY
          resources:
            requests: null
            limits: null
          ports:
            - containerPort: 7946
              name: gossip-ring
      terminationGracePeriodSeconds: 30
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: querier
  namespace: logging
spec:
  template:
    metadata:
      labels:
        gossip_ring_member: "true"
    spec:
      containers:
        - name: querier
          env:
            - name: BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: loki-data-bucket
                  key: BUCKET_NAME
            - name: BUCKET_HOST
              valueFrom:
                configMapKeyRef:
                  name: loki-data-bucket
                  key: BUCKET_HOST
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: loki-data-bucket
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-data-bucket
                  key: AWS_SECRET_ACCESS_KEY
          ports:
            - containerPort: 7946
              name: gossip-ring
          resources:
            requests: null
            limits: null
      terminationGracePeriodSeconds: 30
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memcached
  namespace: logging
spec:
  template:
    spec:
      containers:
        - name: memcached
          resources:
            requests: null
            limits: null
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memcached-frontend
  namespace: logging
spec:
  template:
    spec:
      containers:
        - name: memcached-frontend
          resources:
            requests: null
            limits: null
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memcached-index-queries
  namespace: logging
spec:
  template:
    spec:
      containers:
        - name: memcached
          resources:
            requests: null
            limits: null
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memcached-frontend
  namespace: logging
spec:
  template:
    spec:
      containers:
        - name: memcached
          resources:
            requests: null
            limits: null
---
