apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributor
  namespace: logging
spec:
  minReadySeconds: 10
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: distributor
  strategy:
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 1
  template:
    metadata:
      annotations:
        config_hash: 9ad93d82778c2e2382c21bd5fd197c28
      labels:
        name: distributor
    spec:
      containers:
      - args:
        - -config.file=/etc/loki/config/config.yaml
        - -limits.per-user-override-config=/etc/loki/overrides/overrides.yaml
        - -target=distributor
        env: []
        image: quay.io/cybozu/loki
        imagePullPolicy: IfNotPresent
        name: distributor
        ports:
        - containerPort: 3100
          name: http-metrics
        - containerPort: 9095
          name: grpc
        readinessProbe:
          httpGet:
            path: /ready
            port: 3100
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          limits:
            memory: 5Gi
          requests:
            cpu: 500m
            memory: 2500Mi
        volumeMounts:
        - mountPath: /etc/loki/config
          name: loki
        - mountPath: /etc/loki/overrides
          name: overrides
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            name: distributor
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
      volumes:
      - configMap:
          name: loki
        name: loki
      - configMap:
          name: overrides
        name: overrides
