apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memcached
  namespace: logging
spec:
  replicas: 3
  selector:
    matchLabels:
      name: memcached
  serviceName: memcached
  template:
    metadata:
      labels:
        name: memcached
    spec:
      containers:
      - args:
        - -m 4096
        - -I 2m
        - -c 1024
        - -v
        image: quay.io/cybozu/memcached
        imagePullPolicy: IfNotPresent
        name: memcached
        ports:
        - containerPort: 11211
          name: client
        resources:
          limits:
            cpu: "3"
            memory: 6Gi
          requests:
            cpu: 500m
            memory: 5016Mi
      - args:
        - --memcached.address=localhost:11211
        - --web.listen-address=0.0.0.0:9150
        image: quay.io/cybozu/memcached-exporter
        imagePullPolicy: IfNotPresent
        name: exporter
        ports:
        - containerPort: 9150
          name: http-metrics
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            name: memcached
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
  updateStrategy:
    type: RollingUpdate
