apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: logging
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: promtail
    app.kubernetes.io/version: 2.6.1
    helm.sh/chart: promtail-6.6.2
  name: logging-promtail
  namespace: logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: logging
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: promtail
    app.kubernetes.io/version: 2.6.1
    helm.sh/chart: promtail-6.6.2
  name: logging-promtail
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: logging
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: promtail
    app.kubernetes.io/version: 2.6.1
    helm.sh/chart: promtail-6.6.2
  name: logging-promtail
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: logging-promtail
subjects:
- kind: ServiceAccount
  name: logging-promtail
  namespace: logging
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: logging
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: promtail
    app.kubernetes.io/version: 2.6.1
    helm.sh/chart: promtail-6.6.2
  name: logging-promtail
  namespace: logging
stringData:
  promtail.yaml: "server:\n  log_level: info\n  http_listen_port: 3101\n  \n\nclients:\n
    \ - url: http://distributor.logging:3100/loki/api/v1/push\n\npositions:\n  filename:
    /run/promtail/positions.yaml\n\nscrape_configs:\n  # See also https://github.com/grafana/loki/blob/master/production/ksonnet/promtail/scrape_config.libsonnet
    for reference\n  - job_name: kubernetes-pods\n    pipeline_stages:\n      - cri:
    {}\n    kubernetes_sd_configs:\n      - role: pod\n    relabel_configs:\n      -
    source_labels:\n          - __meta_kubernetes_pod_controller_name\n        regex:
    ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?\n        action: replace\n        target_label:
    __tmp_controller_name\n      - source_labels:\n          - __meta_kubernetes_pod_label_app_kubernetes_io_name\n
    \         - __meta_kubernetes_pod_label_app\n          - __tmp_controller_name\n
    \         - __meta_kubernetes_pod_name\n        regex: ^;*([^;]+)(;.*)?$\n        action:
    replace\n        target_label: app\n      - source_labels:\n          - __meta_kubernetes_pod_label_app_kubernetes_io_instance\n
    \         - __meta_kubernetes_pod_label_release\n        regex: ^;*([^;]+)(;.*)?$\n
    \       action: replace\n        target_label: instance\n      - source_labels:\n
    \         - __meta_kubernetes_pod_label_app_kubernetes_io_component\n          -
    __meta_kubernetes_pod_label_component\n        regex: ^;*([^;]+)(;.*)?$\n        action:
    replace\n        target_label: component\n      - action: replace\n        source_labels:\n
    \       - __meta_kubernetes_pod_node_name\n        target_label: node_name\n      -
    action: replace\n        source_labels:\n        - __meta_kubernetes_namespace\n
    \       target_label: namespace\n      - action: replace\n        replacement:
    $1\n        separator: /\n        source_labels:\n        - namespace\n        -
    app\n        target_label: job\n      - action: replace\n        source_labels:\n
    \       - __meta_kubernetes_pod_name\n        target_label: pod\n      - action:
    replace\n        source_labels:\n        - __meta_kubernetes_pod_container_name\n
    \       target_label: container\n      - action: replace\n        replacement:
    /var/log/pods/*$1/*.log\n        separator: /\n        source_labels:\n        -
    __meta_kubernetes_pod_uid\n        - __meta_kubernetes_pod_container_name\n        target_label:
    __path__\n      - action: replace\n        regex: true/(.*)\n        replacement:
    /var/log/pods/*$1/*.log\n        separator: /\n        source_labels:\n        -
    __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash\n        - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash\n
    \       - __meta_kubernetes_pod_container_name\n        target_label: __path__\n
    \ \n  #\n  # Added by neco\n  #\n  - job_name: kubernetes-apiservers\n    static_configs:\n
    \     - targets:\n          - localhost\n        labels:\n          job: kubernetes-apiservers\n
    \         __path__: /var/log/audit/*.log\n    relabel_configs:\n      - target_label:
    type\n        replacement: audit\n      - target_label: instance\n        replacement:
    ${HOSTNAME}\n    pipeline_stages:\n      - json:\n          expressions:\n            timestamp:
    stageTimestamp\n      - timestamp:\n          format: RFC3339Nano\n          source:
    timestamp\n  - job_name: journal\n    journal:\n      json: false\n      max_age:
    12h\n      path: /var/log/journal\n      labels:\n        job: systemd-journal\n
    \       instance: ${HOSTNAME}\n    relabel_configs:\n      - source_labels: [\"__journal__systemd_unit\"]\n
    \       target_label: \"unit\"\n      - source_labels: [\"__journal__systemd_unit\"]\n
    \       regex: ^session-\\d+\\.scope$\n        target_label: \"unit\"\n        replacement:
    session.scope\n      - source_labels: [\"__journal__systemd_unit\"]\n        regex:
    ^sshd@\\d+-\\d+\\.\\d+\\.\\d+\\.\\d+:\\d+-\\d+\\.\\d+\\.\\d+\\.\\d+:\\d+\\.service$\n
    \       target_label: \"unit\"\n        replacement: sshd.service\n      - source_labels:
    [\"__journal_syslog_identifier\"]\n        target_label: \"syslog_identifier\"\n
    \     - source_labels: [\"__journal_container_name\"]\n        target_label: \"container_name\"\n
    \     - source_labels: [\"__journal__hostname\"]\n        target_label: \"hostname\"\n
    \ \n\nlimits_config:\n"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/instance: logging
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: promtail
    app.kubernetes.io/version: 2.6.1
    helm.sh/chart: promtail-6.6.2
  name: logging-promtail
  namespace: logging
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: logging
      app.kubernetes.io/name: promtail
  template:
    metadata:
      annotations:
        checksum/config: a7f71413ecf0f8c55ce7cda193081acc72469b417fa2dabf705bbc5490084573
      labels:
        app.kubernetes.io/instance: logging
        app.kubernetes.io/name: promtail
    spec:
      containers:
      - args:
        - -config.file=/etc/promtail/promtail.yaml
        - -config.expand-env=true
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: quay.io/cybozu/promtail:2.6.1.1
        imagePullPolicy: IfNotPresent
        name: promtail
        ports:
        - containerPort: 3101
          name: http-metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - DAC_READ_SEARCH
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /etc/promtail
          name: config
        - mountPath: /run/promtail
          name: run
        - mountPath: /var/lib/docker/containers
          name: containers
          readOnly: true
        - mountPath: /var/log/pods
          name: pods
          readOnly: true
        - mountPath: /var/log/audit
          name: audit
          readOnly: true
        - mountPath: /var/log/journal
          name: journal
          readOnly: true
      enableServiceLinks: true
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      serviceAccountName: logging-promtail
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      volumes:
      - name: config
        secret:
          secretName: logging-promtail
      - hostPath:
          path: /run/promtail
        name: run
      - hostPath:
          path: /var/lib/docker/containers
        name: containers
      - hostPath:
          path: /var/log/pods
        name: pods
      - hostPath:
          path: /var/log/audit
        name: audit
      - hostPath:
          path: /run/log/journal
        name: journal
  updateStrategy: {}
